git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --features gruvmax-fang --diff-so-fancy
    #pager: delta --dark --paging=never --features woolly-mammoth --diff-so-fancy
    #pager: delta --dark --paging=never --syntax-theme gruvbox-dark --diff-so-fancy
    #pager: delta --dark --paging=never --syntax-theme gruvbox-dark
    #pager: delta --dark --paging=never --syntax-theme Coldark-Dark
    #pager: delta --dark --paging=never --syntax-theme base16-256
  autoFetch: false
gui:
  showIcons: true
os:
  editCommand: "nvim"
