#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/pochy/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

#nm-applet &
gnome-setting-daemon &
gnome-keyring-daemon --start --components=secrets &
nm-applet --sm-disable &
gnome-power-manager &
gnome-volume-control-applet &
#dropbox start -i &
wbar -above-desk -p top -isize 30 -nanim 7 &
thunar --daemon &
conky &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/pochy/.fluxbox/log"
