# delete
# :call map(dein#check_clean(), "delete(v:val, 'rf')")
# :call dein#recache_runtimepath()
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-scripts/xoria256.vim'

#[[plugins]]
#repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# [[plugins]]
# repo = 'leafgarland/typescript-vim'

# [[plugins]]
# repo = 'peitalin/vim-jsx-typescript'


# [[plugins]]
# repo = 'othree/yajs.vim'

# [[plugins]]
# repo = 'othree/es.next.syntax.vim'

# [[plugins]]
# repo = 'MaxMEllon/vim-jsx-pretty'
# hook_add = '''
# let g:vim_jsx_pretty_colorful_config = 1
# " let g:vim_jsx_pretty_disable_tsx = 1
# '''

# [[plugins]]
# repo = 'pangloss/vim-javascript'
# hook_add = '''
# set conceallevel=1
# let g:javascript_plugin_jsdoc = 1
# let g:javascript_plugin_flow = 1
# '''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = '0'
