# on_i 1を指定すると、インサートモードに入った時に読み込まれます
# on_ft 指定したファイルタイプの時に読み込まれます
# on_path バッファ名が一致した時に読み込まれます。.*を指定すると何かのファイルを開いた時に読み込まれるので、filerなどのプラグインで使うと便利です
# on_source 記載されたプラグインが読み込まれた後に読み込まれます
#on_cmd コマンドが実行された時に読み込まれます。['Unite', 'UniteResume']のようなプラグインのコマンドを指定するかと思います
# on_map on_cmdのマッピング版で['<Plug>(neosnippet_expand_or_jump)']のように指定します
# depends プラグイン間で依存性がある場合に使います。ここに記述しても自動的にインストールされるわけじゃない点はneobundle.vimとは少し挙動が違うので要注意の人もいるかもしれません
# if 'has("nvim") などのように書いて条件に一致した場合のみ読み込まれます
[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

#[[plugins]]
#repo = 'Shougo/neocomplete'
#if = 'has("lua")'
#on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'thinca/vim-quickrun.git'

[[plugins]]
repo = 'thinca/vim-ref.git'

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

[[plugins]]
repo = 'vim-scripts/EnhCommentify.vim'
on_i = 1

[[plugins]]
repo = 'mbbill/undotree'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 't9md/vim-textmanip.git'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Quramy/tsuquyomi'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'othree/es.next.syntax.vim'

#[[plugins]]
#repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'elzr/vim-json'
hook_add = 'let g:vim_json_syntax_conceal = 0'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'ternjs/tern_for_vim'

[[plugins]]
repo = 'ryanolsonx/vim-lsp-typescript'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
